apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Deployment
    metadata:
      name: postgres-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgres
      template:
        metadata:
          labels:
            app: postgres
        spec:
          containers:
            - name: postgres-container
              image: anandsk10/postgres_v_01:postgres_V_1.0
              env:
                - name: POSTGRES_USER
                  value: postgres
                - name: POSTGRES_PASSWORD
                  value: root
                - name: POSTGRES_DB
                  value: server_project
              ports:
                - containerPort: 5432
                  name: postgres
              volumeMounts:
                - name: postgres-volume
                  mountPath: /var/lib/postgresql/data
          volumes:
            - name: postgres-volume
              emptyDir: {}
  
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgres-service
    spec:
      selector:
        app: postgres
      ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: go-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: go
      template:
        metadata:
          labels:
            app: go
        spec:
          containers:
            - name: go-container
              image: anandsk10/golang-api:api_V_1.0
              ports:
                - containerPort: 5002
                  name: go
              volumeMounts:
                - name: go-volume
                  mountPath: /app
          volumes:
            - name: go-volume
              emptyDir: {}
  
  - apiVersion: v1
    kind: Service
    metadata:
      name: go-service
    spec:
      selector:
        app: go
      ports:
        - protocol: TCP
          port: 5002
          targetPort: 5002
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: node-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: node
      template:
        metadata:
          labels:
            app: node
        spec:
          containers:
            - name: node-container
              image: anandsk10/ui:react
              ports:
                - containerPort: 3000
                  name: node
              volumeMounts:
                - name: node-volume
                  mountPath: /app
          volumes:
            - name: node-volume
              emptyDir: {}
  
  - apiVersion: v1
    kind: Service
    metadata:
      name: node-service
    spec:
      selector:
        app: node
      ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
